"use client";
import { useEffect, useMemo, useState } from "react";
type Status = "yes" | "no" | "maybe";
const events = [
  { id: "rh1", name: "Roch Hachana · 1er jour", date: "Samedi 12 septembre 2026", place: "Suissa" },
  { id: "rh2", name: "Roch Hachana · 2e jour", date: "Dimanche 13 septembre 2026", place: "Nakache" },
  { id: "kippour", name: "Kippour", date: "Lundi 21 septembre 2026", place: "À décider" },
  { id: "sukkot", name: "Sukkot", date: "Samedi 26 septembre 2026", place: "Nakache" },
  { id: "simhat", name: "2e fête · Sim'hat Torah", date: "Dimanche 4 octobre 2026", place: "Suissa" },
];
const initialNames = ["Personne 1", "Personne 2", "Personne 3", "Personne 4", "Personne 5"];
const statuses: { key: Status; label: string; icon: string }[] = [{ key: "yes", label: "Je viens", icon: "✓" }, { key: "maybe", label: "À confirmer", icon: "?" }, { key: "no", label: "Absent", icon: "–" }];
export default function Home() {
  const [names, setNames] = useState(initialNames); const [attendance, setAttendance] = useState<Record<string, Status>>({}); const [ready, setReady] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("planning-fetes-2026"); if (saved) try { const data = JSON.parse(saved) as { names?: string[]; attendance?: Record<string, Status> }; if (data.names?.length === 5) setNames(data.names); if (data.attendance) setAttendance(data.attendance); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem("planning-fetes-2026", JSON.stringify({ names, attendance })); }, [names, attendance, ready]);
  const comingCount = useMemo(() => events.reduce((total, event) => total + names.filter((_, index) => attendance[`${event.id}-${index}`] === "yes").length, 0), [attendance, names]);
  const setStatus = (eventId: string, personIndex: number, status: Status) => setAttendance((current) => ({ ...current, [`${eventId}-${personIndex}`]: status }));
  const updateName = (index: number, name: string) => setNames((current) => current.map((item, itemIndex) => itemIndex === index ? name : item));
  const reset = () => { if (confirm("Remettre le planning à zéro ?")) { setNames(initialNames); setAttendance({}); } };
  return <main><section className="hero"><div className="eyebrow">Tichri 5787 · 2026</div><h1>Qui vient aux fêtes ?</h1><p>Un petit planning familial pour que tout le monde sache où et quand se retrouver.</p><div className="hero-note"><span>♥</span> {comingCount} présence{comingCount > 1 ? "s" : ""} enregistrée{comingCount > 1 ? "s" : ""}</div></section><section className="names" aria-labelledby="names-title"><div><h2 id="names-title">La famille</h2><p>Écrivez les prénoms des 5 frères et sœurs.</p></div><div className="name-grid">{names.map((name, index) => <label key={index} className="name-field"><span>{index + 1}</span><input aria-label={`Prénom de la personne ${index + 1}`} value={name} onChange={(event) => updateName(index, event.target.value)} /></label>)}</div></section><section className="planner" aria-labelledby="planner-title"><div className="section-title"><div><h2 id="planner-title">Le planning</h2><p>Chaque personne choisit sa réponse pour chaque repas.</p></div><button className="reset" onClick={reset}>Réinitialiser</button></div><div className="legend"><span><b className="yes">✓</b> Je viens</span><span><b className="maybe">?</b> À confirmer</span><span><b className="no">–</b> Absent</span></div><div className="event-list">{events.map((event) => <article className="event" key={event.id}><header><div className="calendar"><strong>{event.date.split(" ")[0].slice(0, 3)}</strong><span>{event.date.match(/\d+/)?.[0]}</span></div><div><h3>{event.name}</h3><p>{event.date} <i>·</i> <b>{event.place}</b></p></div></header><div className="responses">{names.map((name, personIndex) => { const current = attendance[`${event.id}-${personIndex}`]; return <div className="response" key={personIndex}><span className="person-name">{name.trim() || `Personne ${personIndex + 1}`}</span><div className="choices" aria-label={`Présence de ${name} pour ${event.name}`}>{statuses.map((status) => <button key={status.key} title={status.label} aria-label={status.label} className={`${status.key} ${current === status.key ? "selected" : ""}`} onClick={() => setStatus(event.id, personIndex, status.key)}>{status.icon}</button>)}</div></div>; })}</div></article>)}</div></section><p className="footnote">Les réponses sont enregistrées sur cet appareil.</p></main>;
}
